spring:
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/danblog?serverTimezone=UTC&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
      multipart:
        max-file-size: 100MB
mybatis:
  type-aliases-package: com.huang.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8081
